### ISSUE TITLE
Grid Support

### ISSUE THREAD

**Issue by coltonbrugger** [wesbaker/category_select.ee2_addon#9]
Any chance you'll update this to have Grid support any time soon? If not, I may try my hand at submitting a commit to do so... 

I've used this in several projects to allow clients category-specific personalizations in a Matrix setting. Would love to be able to use it with Grid.

Thanks,

cb

**Comment by brownbike** [comment]
Did the port to Grid ever happen? @coltonbrugger @wesbaker Is there an alternative you can recommend for grid and for EE3?

**Comment by wesbaker** [comment]
No it hasn't and I'm not likely to get to it. If you're interested in trying feel free to submit a pull request.
